---
title: "iccat-spillover-main"
author: "Julia Lawson, UCSB"
date: "4/27/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(reshape2)
library(fixest)
library(broom)
library(haven)
library(stargazer)
here()

#Cleaning data
iccat <- read.csv(here("data", "t1nc-ALL_20201218.csv"),
                  stringsAsFactors = F) %>% 
  unite(FleetGear, c(Fleet,GearGrp), sep=".", remove=FALSE)

#Isolating fleets that catch TAC-managed species.
iccat.fleets <- iccat %>% 
  filter(Species == "BFT" | Species == "SWO" | Species == "ALB" | Species == "BET"| Species == "YFT" | Species == "WHM"| Species == "BUM" | Species == "BSH" | Species == "RSP") %>% 
  group_by(Fleet, GearGrp) %>%
  select(Fleet, GearGrp) %>% 
  distinct(Fleet, GearGrp) %>% 
  unite(FleetGear, c(Fleet,GearGrp), sep=".", remove=FALSE)

#Removing general tuna and billfish categories (not identified beyond Genus).
iccat.fil <- left_join(iccat.fleets, iccat, by=c("FleetGear","Fleet","GearGrp")) %>% 
  group_by(FleetGear, ScieName) %>% 
  filter(ScieName != "Thunnini" & ScieName != "Thunnus spp" & ScieName !="Istiophoridae" & ScieName != "Scomberomorus spp")

#Adding TAC year dummy variable, based on year that TAC was implemented (yearTACimp)
iccat_df <- iccat.fil %>%
  mutate(yearTACimp = case_when(
    Species == "BFT" & Stock == "ATW" ~ 1982,
    Species == "SWO" & Stock == "ATN" ~ 1997,
    Species == "SWO" & Stock == "ATS" ~ 1998,
    Species == "ALB" & Stock == "ATS" ~ 1998,
    Species == "BFT" & Stock == "ATE" ~ 1999,
    Species == "ALB" & Stock == "ATN" ~ 2001,
    Species == "BET" & Stock == "A+M" ~ 2005,
    Species == "SBF" & Stock == "A+M" ~ 2006,
    Species == "BUM" & Stock == "A+M" ~ 2013,
    Species == "WHM" & Stock == "A+M" ~ 2013,
    Species == "YFT" & Stock == "ATE" ~ 2013,
    Species == "YFT" & Stock == "ATW" ~ 2013,
    Species == "SWO" & Stock == "MED" ~ 2017,
    Species == "BSH" & Stock == "ATN" ~ 2019,
    Species == "BSH" & Stock == "ATS" ~ 2019)) %>%
  mutate(scaled_tacr = YearC-yearTACimp) %>% 
    mutate(yearTACimp = ifelse(is.na(yearTACimp), 
                                   Inf, yearTACimp),
           tacr = 1 * (YearC >= yearTACimp)) %>%
  mutate(tacever = case_when(
    Species == "BFT" & Stock == "ATW" ~ 1,
    Species == "SWO" & Stock == "ATN" ~ 1,
    Species == "SWO" & Stock == "ATS" ~ 1,
    Species == "ALB" & Stock == "ATS" ~ 1,
    Species == "BFT" & Stock == "ATE" ~ 1,
    Species == "ALB" & Stock == "ATN" ~ 1,
    Species == "BET" & Stock == "A+M" ~ 1,
    Species == "SBF" & Stock == "A+M" ~ 1,
    Species == "BUM" & Stock == "A+M" ~ 1,
    Species == "WHM" & Stock == "A+M" ~ 1,
    Species == "YFT" & Stock == "ATE" ~ 1,
    Species == "YFT" & Stock == "ATW" ~ 1,
    Species == "SWO" & Stock == "MED" ~ 1,
    Species == "BSH" & Stock == "ATN" ~ 1,
    Species == "BSH" & Stock == "ATS" ~ 1)) %>%
    mutate(tacever = ifelse(is.na(tacever), 0, tacever))

write.csv(iccat_df, here("data", "iccat_df_unedited.csv"), row.names = F)

#Accumulation of stocks over time, increase in reporting.
iccat_1970 <- iccat_df %>% 
  filter(YearC == 1970) %>% 
  ungroup() %>% 
  distinct(ScieName)
iccat_2019 <- iccat_df %>% 
  filter(YearC == 2019) %>% 
  ungroup() %>% 
  distinct(ScieName)
incommon <- inner_join(iccat_2019, iccat_1970)

#There has been an increase in fleets (FleetGear) over time. 196 FleetGear in 2019, 41 in 1970.
#iccat_fg_1970 <- iccat_df %>% 
#  filter(YearC == 1970) %>% 
#  ungroup() %>% 
#  distinct(FleetGear)
#iccat_fg_2019 <- iccat_df %>% 
#  filter(YearC == 2019) %>% 
#  ungroup() %>% 
#  distinct(FleetGear)
#incommon_fg <- inner_join(iccat_fg_2019, iccat_fg_1970)

#There are 63 stock groups that have been added between 1970 and 2019. I am removing them so that the numbers are not inflated as new stocks are reported over time. Only stocks that are "in common" in 1970 and 2019 will be retained. 
#There has been an increase in fleets over time. I am only including fleets that have remained part of ICCAT from 1970 to 2019.

iccat_df_final <- left_join(incommon, iccat_df, by="ScieName") %>% 
  unite(SpeciesStock, c(Species,Stock), sep=".", remove=FALSE) #%>% 
#  left_join(incommon_fg, by="FleetGear")

#isolating just the fleets that span from 1970 to 2019
filter <- iccat_df_final %>% 
  filter(YearC >= 1970 & YearC <= 2019) %>% 
  select(YearC, FleetGear,SpeciesStock) %>% 
  distinct(YearC, FleetGear) %>% 
  count(FleetGear) %>% 
  filter(n>=45) %>% 
  select(FleetGear)

```

```{r prices}

#Cleaning price data from NOAA
noaa.prices <- read.csv(here("data", "foss_landings.csv"),
                  stringsAsFactors = F)
noaa.prices$Dollars <- as.numeric(gsub(",","",noaa.prices$Dollars))
noaa.prices$Pounds <- as.numeric(gsub(",","",noaa.prices$Pounds))

noaa.prices_edit <- noaa.prices %>% 
  mutate(SpeciesID = case_when(
    NMFS.Name == "TUNA, BLUEFIN" ~ "BFT",
    NMFS.Name == "TUNA, SKIPJACK" ~ "SKJ",
    NMFS.Name == "SHARK, MAKO, SHORTFIN" ~ "SMA",
    NMFS.Name == "MARLIN, BLUE" ~ "BUM",
    NMFS.Name == "TUNA, ALBACORE" ~ "ALB",
    NMFS.Name == "TUNA, YELLOWFIN" ~ "YFT",
    NMFS.Name == "SHARK, BLUE" ~ "BSH",
    NMFS.Name == "TUNA, BIGEYE" ~ "BET",
    NMFS.Name == "TUNA, BLACKFIN" ~ "BLF",
    NMFS.Name == "TUNA, BLACKFIN" ~ "LTA")) %>% 
  na.omit(SpeciesID) %>% 
  filter(Region.Name!="Gulf") %>% 
  group_by(Year,SpeciesID) %>% 
  mutate(Kilogram = Pounds*0.453592) %>% 
  mutate(USDperkilo = Kilogram/Dollars) %>% 
  summarize(avUSDperkilo = mean(USDperkilo)) %>% 
  filter(avUSDperkilo <= 80) %>% 
  rename(YearC=Year) %>% 
  rename(Species=SpeciesID)
  
#ggplot(noaa.prices_edit, aes(x=YearC, y=avUSDperkilo, color=Species)) +
#  geom_line()

```

```{r cleaned dataset}

#Creating a tac_any column, which shows in a given fleet year (grouped by FleetGear and YearC) if there are any stocks that are catch regulated (1 if at least one TAC-regulated stock is in the catch, 0 if none)
iccat_df_final_edit <- filter %>% 
  left_join(iccat_df_final, by="FleetGear") %>%
  left_join(noaa.prices_edit, by = c("Species","YearC")) %>% 
#  filter(GearGrp=="PS") %>%  #Adding in a filter for just Purse Seine fleets
  group_by(YearC, FleetGear) %>% 
  mutate(tac_any = case_when(any(tacr == 1) ~ 1, TRUE ~ 0)) %>% 
  group_by(YearC, FleetGear) %>% 
  mutate(totalFleetCatch = sum(Qty_t)) %>%
  mutate(propStock = Qty_t/totalFleetCatch) %>% 
  group_by(FleetGear, SpeciesStock) %>% 
  mutate(diff=propStock-lag(propStock,k=1)) %>%
  mutate(Qtydiff=Qty_t-lag(Qty_t,k=1)) %>%
  group_by(FleetGear) #%>% 
  #filter(YearC >= 1970 & YearC <= 2019) #%>% 
  #na.omit(avUSDperkilo) #here I'm removing all stocks that didn't have pricing in the NOAA database. Reduces sample size.

write.csv(iccat_df_final_edit, here("data", "iccat_df_edited.csv"), row.names = F)

```

```{r analaysis by stock}
#Question. Does the proportion of the catch of stocks that never receive a TAC increase or decrease relative to the catch of stocks that eventually receive a TAC?
#Answer. The sign is positive, suggesting that the proportion of the catch of non-TAC stocks increases following TAC implementation. However the difference is not statistically significant, suggesting that the effect of this leakage is minimal.

stockreg <- feols(propStock ~ tacever | YearC^SpeciesStock + FleetGear + avUSDperkilo, data = filter(iccat_df_final_edit, tacr==0))
stockreg_coef_tab <- stockreg$coeftable

```


```{r analysis by price}

#Question. Does the value of the stocks that never receive a TAC increase or decrease relative to stocks that do eventually receive a TAC? 
#Answer: The sign is positive, suggesting that prices of non-TAC regulated stocks increase following TAC implementation, however the difference is not statistically significant suggesting that the price increase is relatively minimal.

pricereg <- feols(avUSDperkilo ~ tacever | YearC^SpeciesStock + FleetGear + log(Qty_t), data = filter(iccat_df_final_edit, tacr==0))
pricereg_coef_tab <- pricereg$coeftable

```

```{r analaysis by fleet}
#Question. Does the proportion of the catch of non-TAC stocks in fleets that are catching one or more TAC stock increase or decrease relative to the catch of non-TAC stocks in fleets that do not catch any TAC stocks?
#Answer. The treatment (being a fleet that catches one or more TAC stock) catch of non-TAC stocks in fleets that are catching one or more TAC stock increase 

fleetreg <- feols(propStock ~ tac_any | YearC^SpeciesStock + FleetGear, data = filter(iccat_df_final_edit, tacr==0))
fleetreg_coef_tab <- fleetreg$coeftable

```

```{r analysis}

#Regression 1. ----
#Question: Does the catch of non-TAC stocks in fleets that are catching one or more TAC stock increase or decrease relative to the catch of non-TAC stocks in fleets that do not catch any TAC stocks?
#Answer from the regression output: Fleets that catch one or more TAC stock increase their catch by 10.89 metric tons, relative to fleets that do not catch any TAC stocks.

# tac_reg1 <- lm(Qty_t ~ tac_any + as.factor(YearC) + FleetGear + SpeciesStock, data = filter(iccat_df_final_edit, tacr==0))
# summary(tac_reg1) #matches feols output
#mb, 5.3.21: commenting out for speed, made YearC into a categorical FE

tac_reg1b <- feols(Qty_t ~ tac_any | YearC + FleetGear + SpeciesStock, data = filter(iccat_df_final_edit, tacr==0))
coef_tab <- tac_reg1b$coeftable
#This regression assumes that all stocks change in the same way over time (this is the YearC fixed effect on its own)

tac_reg1c <- feols(Qty_t ~ tac_any | YearC^SpeciesStock + FleetGear, data = filter(iccat_df_final_edit, tacr==0)) #mb: adding year-by-speciesstock FEs
coef_tab <- tac_reg1c$coeftable
#result: positive, significant spillover when adding FEs that account for variations in stock-by-year
#JML: Answer from regression output: The total catch of non-TAC regulated stocks (SpeciesStock) increases by 113.40 metric tons for fleets (FleetGear) that catch at least one TAC managed stock (tac_any = 1), when SpeciesStock is interacted with year (when we allow for each stock to individually vary over time). 

#Regression 2. ----
#Creating a column that is proportion of TAC-treated stocks in total catch (prop_tacC).
#iccat_df_final_test2 <- iccat_df_final_edit %>% 
#  group_by(YearC, FleetGear) %>% 
#  mutate(totalCatch = sum(Qty_t),
#         tac_catch = sum(Qty_t[tacr==1])) %>% #Total catch grouped by FleetGear and YearC
#  mutate(prop_tacC = tac_catch/totalCatch) #mb: notice this is different

#hist(iccat_df_final_test2$prop_tacC)
#JML: commented out Mark's code (above) to try new code (below)

#Creating a column that is the proportion of TAC-treated stocks in total catch in years prior to when the TAC went into effect (prop_tacCpre)
#Proportion of TAC catch (tacever=1) in the years before the TAC went into effect (tacr=0) for each stock
iccat_df_final_reg <- iccat_df_final_edit %>% 
  group_by(YearC, FleetGear) %>% 
  mutate(totalCatch = sum(Qty_t),
         pretac_catch = sum(Qty_t[tacever==1 & tacr==0])) %>% 
  mutate(prop_pretac_catch = pretac_catch/totalCatch)

#Question. Does the proportion of TAC-treated stocks in a given fleet's total catch increase or decrease relative to the proportion of non-TAC treated stocks following TAC implementation?
#Answer from the regression:  The proportion of stocks that would be subject to TAC restrictions (tacever=1, tacr=0) in a given fleet's total catch, were 316X higher in the years prior to TAC implementation (tacr=0) compared to the years after TAC restrictions were in place.

# tac_reg2 <- lm(Qty_t ~ tac_any*prop_tacC + as.factor(YearC) + FleetGear + SpeciesStock, data = filter(iccat_df_final_reg, tacr==0))
# summary(tac_reg2)
# 
# tac_reg2b <- feols(Qty_t ~ tac_any*prop_tacC | YearC + FleetGear + SpeciesStock, data = filter(iccat_df_final_reg, tacr==0))
# # print(tac_reg2b)

tac_reg2c <- feols(Qty_t ~ prop_pretac_catch | YearC^SpeciesStock + FleetGear, data = filter(iccat_df_final_reg, tacr==0))
coef_tab <- tac_reg2c$coeftable

#note: this isn't strictly right, because we probably want the dosage based on the pre-treatment period only

```

