---
title: "iccat-taccaps"
author: "Julia Lawson, UCSB"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(ggpubr)
library(kableExtra)
library(reshape2)
here()

iccat_df <- read.csv(here("data", "iccat_df_edited.csv"),
                  stringsAsFactors = F) %>% 
  unite(SpeciesStock, c(Species,Stock), sep=".", remove=FALSE) 

ccsbt_data <- read.csv(here("data", "CCSBT_totalSBT.csv"),
                  stringsAsFactors = F) %>% 
  rename(totProd=Catch) %>% 
  mutate(scaled_tacr = Year-2007) %>% 
  add_column(SpeciesStock="SBF")

eastern.med.bft <- iccat_df %>% 
  filter(SpeciesStock =="BFT.ATE" | SpeciesStock =="BFT.MED") %>% 
  group_by(YearC) %>% 
  summarize(totProd=sum(Qty_t)) %>% 
  add_column(SpeciesStock="BFT.AE+M") %>% 
  mutate(scaled_tacr = YearC-1999) %>% 
  rename(Year=YearC)

```

```{r import tac caps and scrs advice}
taccaps <- read.csv(here("data", "taccaps.csv"),
                  stringsAsFactors = F) %>% 
  rename(SpeciesStock=stockID)

scrsad <- read.csv(here("data", "scrsadvice.csv"),
                  stringsAsFactors = F) %>% 
  rename(SpeciesStock=stockID) %>% 
  rename(Year=RepYear) %>% 
  na.omit()

iccat.reduced <- iccat_df %>% 
  filter(tacever=="1") %>% 
  filter(SpeciesStock != "BSH.ATN" & SpeciesStock != "BSH.ATS"& SpeciesStock != "YFT.ATE"& SpeciesStock != "YFT.ATW"& SpeciesStock != "SWO.MED"& SpeciesStock != "WHM.A+M"& SpeciesStock != "BUM.A+M" & SpeciesStock != "SBF.A+M") %>% 
  select(YearC, Qty_t, SpeciesStock, scaled_tacr) %>% 
  rename(Year=YearC) %>% 
  group_by(Year, scaled_tacr, SpeciesStock) %>% 
  summarize(totProd=sum(Qty_t)) %>% 
  bind_rows(ccsbt_data) %>% 
  bind_rows(eastern.med.bft)

iccat.combo <- left_join(iccat.reduced, taccaps) %>% 
  right_join(scrsad, by=c("Year","SpeciesStock"))

taccapsplot <- ggplot(data=iccat.combo) +
  theme_bw() +
  geom_point(aes(x=Year, y=tac_cap, color=SpeciesStock)) + 
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1980,2012)

taccapsplot

##Breaking into three groups
iccat.combo.grp1 <- iccat.combo %>% 
  filter(SpeciesStock=="SWO.ATS" | SpeciesStock=="BFT.ATW" | SpeciesStock=="ALB.ATN" )

taccapsplot.grp1 <- ggplot(data=iccat.combo.grp1) +
  theme_bw() +
  geom_point(aes(x=Year, y=tac_cap, color=SpeciesStock), shape="-", size=8) +
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1980,2012)
taccapsplot.grp1

iccat.combo.grp2 <- iccat.combo %>% 
  filter(SpeciesStock=="SBF" | SpeciesStock=="BET.A+M" | SpeciesStock=="ALB.ATS")

taccapsplot.grp2 <- ggplot(data=iccat.combo.grp2) +
  theme_bw() +
  geom_point(mapping=aes(x=Year, y=tac_cap, color=SpeciesStock), shape="-", size=8) +
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1997,2012)
taccapsplot.grp2

iccat.combo.grp3 <- iccat.combo %>% 
  filter(SpeciesStock=="SWO.ATN" | SpeciesStock=="BFT.AE+M")

taccapsplot.grp3 <- ggplot(data=iccat.combo.grp3) +
  theme_bw() +
  geom_point(mapping=aes(x=Year, y=tac_cap, color=SpeciesStock), shape="-", size=8) +
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1995,2012)
taccapsplot.grp3

#Breaking into two groups according to constraining/maintaining 
#Constraining Group [Group 1 - BFT.ATW, SWO.ATN, SWO.ATS, BFT.AE+M, SBT]
iccat.combo.grp1b <- iccat.combo %>% 
  filter(SpeciesStock=="SWO.ATN" | SpeciesStock=="SWO.ATS" |SpeciesStock=="BFT.ATW" | SpeciesStock=="BFT.AE+M" | SpeciesStock=="SBF")

taccapsplot.grp1b <- ggplot(data=iccat.combo.grp1b) +
  theme_bw() +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  geom_point(aes(x=Year, y=tac_cap, color=SpeciesStock), shape="-", size=8) +
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1980,2012)
taccapsplot.grp1b

ggsave(plot = last_plot(), filename = here("visuals/constraining.png"), width = 6, height = 4)

#Maintaining Group [Group 2 - ALB.ATS, ALB.ATN, BET.A+M]
iccat.combo.grp3b <- iccat.combo %>% 
  filter(SpeciesStock=="ALB.ATS" | SpeciesStock=="ALB.ATN" |SpeciesStock=="BET.A+M")

taccapsplot.grp3b <- ggplot(data=iccat.combo.grp3b) +
  theme_bw() +
  geom_line(aes(x=Year, y=totProd, color=SpeciesStock)) +
  geom_point(aes(x=Year, y=tac_cap, color=SpeciesStock), shape="-", size=8) +
  geom_point(aes(x=Year, y=scrs_value, color=SpeciesStock), shape=2) +
  theme(legend.title = element_blank(), legend.position = "bottom") +
  xlab("") + ylab("") +
  xlim(1997,2012)
taccapsplot.grp3b

ggsave(plot = last_plot(), filename = here("visuals/maintaining.png"), width = 6, height = 4)
```


```{r export fig of tac caps}
taccaps <- ggarrange(taccapsplot.grp1b, taccapsplot.grp3b, ncol = 2, nrow = 1)

annotate_figure(taccaps, bottom = "Year", left = "ICCAT Reported Catch (mt)")

ggsave(plot = last_plot(), filename = here("visuals/taccaps_scrsadv.png"), width = 10, height = 4)

```

```{r kobe plot for different tacs}
health <- read.csv(here("data", "healthindicators.csv"),
                  stringsAsFactors = F)
health$Group <- as.character(health$Group)

#Pre-TAC comparing SCRS understanding at the time with Ram Legacy data
health_pre <- health %>% 
  filter(TimePeriod=="0")
healthindi_pre <- ggplot(data=health_pre,aes(x=BvBmsy, y=FvFmsy, color=Group, shape=Dataset)) +
  theme_bw() +
  geom_point(size = 3) +
  geom_vline(xintercept = 1,linetype = "longdash", colour="darkgrey") +
  geom_hline(yintercept = 1,linetype = "longdash", colour="darkgrey") +
  geom_vline(xintercept = 1.05,linetype = "longdash", colour="darkgrey") +
  geom_vline(xintercept = 0.95,linetype = "longdash", colour="darkgrey") +
  geom_text(aes(label=SpeciesStock), nudge_x = 0.04, nudge_y = -0.05, size=2.5) +
  xlab("B/BMSY") + ylab("F/FMSY") +
  scale_color_manual(values = c("#d01c8b", "#e885c1", "#7fda5a", "#4dac26"),
                     labels = c("Constraining", "Leans Constraining", "Leans Maintaining", "Maintaining")) +
  scale_shape_manual(values = c(16,17), 
                     labels = c("Ram Legacy Database", "ICCAT SCRS Report")) +
  theme(legend.text = element_text(size=8), legend.title = element_text(size=8))
healthindi_pre

ggsave(plot = last_plot(), filename = here("visuals/health_bothdata.png"), width = 8, height = 4)

#Just SCRS estimates, and Ram estimates for BFT.ATW, SBT, and BFT.AE+M
health_pre2 <- health %>% 
  filter(TimePeriod=="0") %>% 
  filter(Dataset=="Scrs")
no_scrs_est <- health %>% 
  filter(TimePeriod=="0") %>% 
  filter(SpeciesStock=="BFT.ATW" | SpeciesStock=="SBF" | SpeciesStock=="BFT.AE+M")
sci_advice_pre <- bind_rows(health_pre2, no_scrs_est)

healthindi_pre2 <- ggplot(data=sci_advice_pre,aes(x=BvBmsy, y=FvFmsy, color=Group)) +
  theme_bw() +
  geom_point(size = 4) +
  geom_vline(xintercept = 1,linetype = "longdash", colour="darkgrey") +
  geom_hline(yintercept = 1,linetype = "longdash", colour="darkgrey") +
  geom_vline(xintercept = 1.05,linetype = "longdash", colour="darkgrey") +
  geom_vline(xintercept = 0.95,linetype = "longdash", colour="darkgrey") +
  geom_text(aes(label=SpeciesStock), nudge_x = 0.05, nudge_y = -0.09, size=3) +
  xlab("B/BMSY") + ylab("F/FMSY") +
  scale_color_manual(values = c("#d01c8b", "#e885c1", "#8ace37", "#4dac26"),
                     labels = c("Constraining", "Leans Constraining", "Leans Maintaining", "Maintaining")) +
  theme(legend.title = element_blank(), legend.position = "bottom") #+
  #annotate("text", x=1.2, y=1.3, label= "Maximally Sustainably Exploited (FAO)",color="dark grey",size=3)

healthindi_pre2

#ggsave(plot = last_plot(), filename = here("visuals/health_scrs.png"), width = 6, height = 4)
```